#ifndef POWERPACK_DRONECAN_PARAM_H_
#define POWERPACK_DRONECAN_PARAM_H_

// Hand-coded DroneCAN param.GetSet (ID 11) and param.ExecuteOpcode (ID 10)
// encode/decode. These are not generated by the DSDL compiler in the SINE ESC CAN
// library, so we implement the subset needed for config writing.

#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <canard.h>

// =============================================================================
// param.Value union (tag is 3 bits)
// =============================================================================
// Tag values:
//   0 = empty
//   1 = integer_value (int64)
//   2 = real_value (float32)
//   3 = boolean_value (uint8)
//   4 = string_value (uint8[<=128])

#define PARAM_VALUE_TAG_EMPTY    0
#define PARAM_VALUE_TAG_INTEGER  1
#define PARAM_VALUE_TAG_REAL     2
#define PARAM_VALUE_TAG_BOOLEAN  3
#define PARAM_VALUE_TAG_STRING   4

struct ParamValue {
    uint8_t tag;  // 3-bit union tag
    union {
        int64_t integer_value;
        float real_value;
        uint8_t boolean_value;
        struct {
            uint8_t data[128];
            uint8_t len;
        } string_value;
    };
};

// =============================================================================
// param.GetSet (Service ID 11)
// Signature: 0xA7B622F939D1A4D5
// =============================================================================
#define UAVCAN_PARAM_GETSET_ID 11
#define UAVCAN_PARAM_GETSET_SIGNATURE 0xA7B622F939D1A4D5ULL

struct ParamGetSetRequest {
    uint16_t index;        // uint13 (we use uint16, top 3 bits ignored)
    ParamValue value;      // Value to set (empty = read only)
    char name[93];         // uint8[<=92] name + null terminator
    uint8_t name_len;
};

struct ParamGetSetResponse {
    ParamValue value;      // Actual value after set
    ParamValue default_value;
    char name[93];
    uint8_t name_len;
};

// =============================================================================
// param.ExecuteOpcode (Service ID 10)
// Signature: 0x3B131AC5EB69D2CDULL
// =============================================================================
#define UAVCAN_PARAM_EXECUTEOPCODE_ID 10
#define UAVCAN_PARAM_EXECUTEOPCODE_SIGNATURE 0x3B131AC5EB69D2CDULL

#define PARAM_OPCODE_SAVE  0
#define PARAM_OPCODE_ERASE 1

struct ParamExecuteOpcodeRequest {
    uint8_t opcode;
    int64_t argument;  // int48 - reserved, keep zero
};

struct ParamExecuteOpcodeResponse {
    int64_t argument;  // int48
    bool ok;
};

// =============================================================================
// Encode/Decode functions
// =============================================================================

// Encode a ParamValue into a buffer at bit offset.
// Returns number of bits written.
uint32_t paramValue_encode(const ParamValue* val, uint8_t* buffer, uint32_t bit_ofs);

// Decode a ParamValue from a transfer at bit offset.
// Returns number of bits consumed.
uint32_t paramValue_decode(const CanardRxTransfer* transfer, uint32_t bit_ofs, ParamValue* val);

// Encode param.GetSet request
uint32_t paramGetSetRequest_encode(const ParamGetSetRequest* req, uint8_t* buffer);

// Decode param.GetSet response
bool paramGetSetResponse_decode(const CanardRxTransfer* transfer, ParamGetSetResponse* res);

// Encode param.ExecuteOpcode request
uint32_t paramExecuteOpcodeRequest_encode(const ParamExecuteOpcodeRequest* req, uint8_t* buffer);

// Decode param.ExecuteOpcode response
bool paramExecuteOpcodeResponse_decode(const CanardRxTransfer* transfer, ParamExecuteOpcodeResponse* res);

#endif // POWERPACK_DRONECAN_PARAM_H_
